DROP DATABASE IF EXISTS `zalo_clone`;
DROP USER IF EXISTS `m0tnamk09`@`%`;
CREATE DATABASE IF NOT EXISTS `zalo_clone` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'm0tnamk09'@'%' IDENTIFIED BY '1509';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `zalo_clone`.* TO `m0tnamk09`@`%`;